import { defineSchema, defineTable } from 'convex/server'
import { v } from 'convex/values'

export default defineSchema({
  // Agent definitions and their current state
  agents: defineTable({
    name: v.string(),
    type: v.string(), // 'gig_finder' | 'proposal_writer' | 'work_engine' | 'content_creator' | 'outreach'
    status: v.string(), // 'idle' | 'running' | 'paused' | 'error'
    lastRun: v.optional(v.number()),
    nextRun: v.optional(v.number()),
    runCount: v.number(),
    successCount: v.number(),
    config: v.optional(v.string()), // JSON config
    description: v.string(),
  }).index('by_type', ['type']),

  // Gigs found by the gig finder agent
  gigs: defineTable({
    platform: v.string(), // 'fiverr' | 'upwork' | 'freelancer' | 'direct'
    title: v.string(),
    description: v.string(),
    budget: v.optional(v.string()),
    url: v.optional(v.string()),
    skills: v.array(v.string()),
    status: v.string(), // 'new' | 'proposal_sent' | 'in_progress' | 'completed' | 'rejected' | 'skipped'
    matchScore: v.number(), // 0-100 how well it matches our skills
    proposalDraft: v.optional(v.string()),
    foundAt: v.number(),
    notes: v.optional(v.string()),
  }).index('by_status', ['status'])
    .index('by_platform', ['platform']),

  // Revenue and expenses tracking
  transactions: defineTable({
    type: v.string(), // 'income' | 'expense'
    amount: v.number(),
    description: v.string(),
    category: v.string(), // 'freelance' | 'affiliate' | 'content' | 'api_cost' | 'hosting' | 'other'
    source: v.optional(v.string()), // which agent or gig
    date: v.number(),
  }).index('by_type', ['type'])
    .index('by_category', ['category']),

  // Agent activity log
  activityLog: defineTable({
    agentType: v.string(),
    action: v.string(),
    details: v.string(),
    status: v.string(), // 'success' | 'error' | 'info'
    timestamp: v.number(),
  }).index('by_agent', ['agentType'])
    .index('by_timestamp', ['timestamp']),

  // Content generated by content agent
  content: defineTable({
    type: v.string(), // 'blog_post' | 'social_media' | 'email' | 'proposal' | 'portfolio'
    title: v.string(),
    body: v.string(),
    status: v.string(), // 'draft' | 'approved' | 'published' | 'rejected'
    platform: v.optional(v.string()),
    createdAt: v.number(),
  }).index('by_type', ['type'])
    .index('by_status', ['status']),

  // Alfred's self-awareness / stats
  alfredState: defineTable({
    key: v.string(),
    value: v.string(),
  }).index('by_key', ['key']),
})
